server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create # ??? ? ?? ?? ?????
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource: # db ??
    username: gangnam
    password: gangnam
    url : jdbc:mysql://localhost:3306/login
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  key : woaieyfhk0pq2093!=sadfaiopxc # key ? ? key ? ??? ??? ??? ???? ???.
  time : 86400000 # ??? ?? ?? / ?? ???? ? ??? ??? ??.


